name: ayuda
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/6.jpg
    - assets/7.jpg
    - assets/8.jpg
    - assets/9.jpg
    - assets/10.jpg
    - assets/11.jpg
    - assets/12.jpg
    - assets/pa.jpg
    - assets/asset1.jpg
    - assets/asset2.jpg
    - assets/asset3.jpg
    - assets/asset4.jpg
    - assets/asset5.png
    - assets/asset6.jpg
    - assets/asset7.jpg
    - assets/asset8.jpg
    - assets/asset9.jpg
    - assets/asset10.jpg
    - assets/a1.jpeg
    - assets/a2.jpeg
    - assets/a3.jpeg
    - assets/a4.jpeg
    - assets/a5.jpeg


  
  
splashscreen: ^1.3.0
