name: ayuda
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:

  flutter_launcher_icons: ^0.13.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.png
    - assets/6.jpg
    - assets/7.jpg
    - assets/8.jpg
    - assets/9.jpg
    - assets/pinterest.png
    - assets/13.jpeg
    - assets/14.jpeg 
    - assets/16.jpg
    - assets/20.jpg
    - assets/21.jpg
    - assets/22.jpg
    - assets/24.jpg
    - assets/23.jpg
    - assets/25.jpg
    - assets/26.jpg
    - assets/30.jpg
    - assets/F.jpeg
    
    


  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf

splashscreen: ^1.3.0

flutter_icons:
  image_path: "assets/pinterest.png"
  android: true
  ios: true